### ISSUE TITLE
heightmaps

### ISSUE THREAD

**Issue by Sigma88** [iamcal/World-of-MapCraft#1]
hi there, sorry to bother you,

is it possible to get heightmaps using this tool? I'd love to get some heightmaps to go along with the colormaps found on the site.

btw, this is great!

thanks for you time

Sigma

**Comment by iamcal** [comment]
i don't know! that would be useful data

**Comment by Sigma88** [comment]
I managed to find some heightmaps on some forum, that's why I closed the issue :)
thanks anyways for your reply :+1:
