### ISSUE TITLE
How to add Icon on map?

### ISSUE THREAD

**Issue by rogical** [iamcal/World-of-MapCraft#2]
Hi,

May i know how to add icon on map? eg show npc on map. thanks!!

**Comment by iamcal** [comment]
That's not a feature of the site/app, sorry

**Comment by rogical** [comment]
i can see this one shows npc.  https://www.gamermaps.net/world-of-warcraft/map/#4.15120.19816.0

do they use the same map from you? thanks

**Comment by iamcal** [comment]
That's a different map and unrelated to this code/site 👍

**Comment by rogical** [comment]
thanks!
